version: 0.2

phases:

  install:
    commands:
      - cd /usr/bin
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum install -y terraform-${TF_VERSION}

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -lock=false -input=false
      - terraform workspace select -or-create ${WORKSPACE}
      - terraform apply -auto-approve

      - |
        if [ -z "${WORKSPACE_DIRECTORY}" ]; then 
          terraform apply -auto-approve
        else
          terraform apply -auto-approve -var-file=${WORKSPACE_DIRECTORY}/${WORKSPACE}.tfvars || terraform apply -auto-approve -var-file=${WORKSPACE_DIRECTORY}/${ACCOUNT_NAME}.tfvars
        fi


  post_build:
    commands:
      - echo "apply complete"
