version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Instalando AWS CDK..."
      - npm install -g aws-cdk
      - echo "Instalando dependencias del proyecto en Python..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Validando la aplicación CDK..."
      - cdk synth --app "python ./cet/app.py"

  post_build:
    commands:
      - echo "Desplegando la infraestructura con AWS CDK..."
      - cdk deploy AgentsStack --require-approval never
      - echo "Despliegue completado con éxito."

artifacts:
  files:
    - '**/*'